{{- if .Values.productService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.productService.name }}
  labels:
    {{- include "k8s-compliment-shop.productService.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.productService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.productService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.productService.name }}
        {{- with .Values.productService.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.productService.name }}
        image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
        imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.productService.service.httpPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.productService.service.grpcPort }}
          name: grpc
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.productService.env.aspnetcoreEnvironment | quote }}
        - name: ASPNETCORE_URLS
          value: {{ .Values.productService.env.aspnetcoreUrls | quote }}
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: connection-string
        livenessProbe:
          {{- toYaml .Values.productService.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.productService.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.productService.resources | nindent 10 }}
{{- end }}
