{{- if .Values.webService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webService.name }}
  labels:
    {{- include "k8s-compliment-shop.webService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webService.service.type }}
  selector:
    app: {{ .Values.webService.name }}
  ports:
  - port: {{ .Values.webService.service.port }}
    targetPort: {{ .Values.webService.service.targetPort }}
    protocol: TCP
    name: http
  {{- if .Values.webService.service.sessionAffinity }}
  sessionAffinity: {{ .Values.webService.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.webService.service.sessionAffinityTimeout }}
  {{- end }}
{{- end }}
