{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    {{- include "k8s-compliment-shop.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  {{- if .Values.mysql.service.clusterIP }}
  clusterIP: {{ .Values.mysql.service.clusterIP }}
  {{- end }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
    protocol: TCP
    name: mysql
  selector:
    app: {{ .Values.mysql.name }}
{{- end }}
